### ISSUE TITLE
代码运行请教

### ISSUE THREAD

**Issue by lujiarui-iie** [suntea233/DualLoRA#2]
copy_t5.py 中
```python
print(module.q.lora)
module.q.lora.weight.data.normal_(mean=0.0, std=factor * ((d_model * key_value_proj_dim) ** -0.5))
```
print 行报错：
```
AttributeError: 'ControlPrompt' object has no attribute 'lora'
```
print 下面一行也会存在类似的问题，请问如何解决，非常感谢！

**Comment by lujiarui-iie** [comment]
发现是 `class ConLoRALinear(nn.Linear, LoRALayer)` 没有定义 lora，请问如何解决呢？

**Comment by suntea233** [comment]
您好，这是我们上传代码时疏忽导致，我们版本更新时忘记更新此处。
但按照我们所提供的环境，应该是不会出现这种报错的，而当我们采用更高版本的环境时，确实会在该处报错，只需将对应的lora改成Con即可，我们将修改代码，即：
`module.q.Con.weight.data.normal_(mean=0.0, std=factor * ((d_model * key_value_proj_dim) ** -0.5))`

**Comment by peng913** [comment]
> 发现是 `class ConLoRALinear(nn.Linear, LoRALayer)` 没有定义 lora，请问如何解决呢？

请问您的复现结果与原文相差大嘛

**Comment by lujiarui-iie** [comment]
> > 发现是 `class ConLoRALinear(nn.Linear, LoRALayer)` 没有定义 lora，请问如何解决呢？
> 
> 请问您的复现结果与原文相差大嘛

比较大

**Comment by peng913** [comment]
> > > 发现是 `class ConLoRALinear(nn.Linear, LoRALayer)` 没有定义 lora，请问如何解决呢？
> > 
> > 
> > 请问您的复现结果与原文相差大嘛
> 
> 比较大
我也是，要不加个联系方式交流交流？
