### ISSUE TITLE
SDG数据集运行报错

### ISSUE THREAD

**Issue by peng913** [suntea233/DualLoRA#3]
尊敬的作者您好，我再进行SDG数据集上进行实验运行语言是python train.py --n_epochs 5 --ckpt "./save/models/small" --desc normal --zero_initialization lora，出现了显示.index() 方法查找一个元素（'what is the city or area where user wants to search for a therapist?'），但这个元素不在 self.dev_desc 列表中。具体来说，在 train.py 的第 309 行，代码试图通过 batch['slot_description'] 中的元素，查找它们在 self.dev_desc 的位置 @
[报错记录.docx](https://github.com/user-attachments/files/17658797/default.docx)

**Comment by suntea233** [comment]
您好，需要将在运行脚本上添加--dataset sgd即可，还需要将copy_data_loader.py上的[101-102](https://github.com/suntea233/DualLoRA/blob/main/copy_data_loader.py#L101-L102)行代码取消注释，我们也将对代码进行修改
